# version key is obsolete in newer Docker Compose — safe to remove
services:
  chrome:
    image: selenium/node-chrome:4.34.0
    shm_size: 2gb
    deploy:
      replicas: 1
    depends_on:
      - selenium-hub
    extra_hosts:
      - "localhost:host-gateway"   # ✅ to map host's localhost inside the container
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
 
#  firefox:
#    image: selenium/node-firefox:4.34.0
#    shm_size: 2gb
#    deploy:
#      replicas: 1
#    depends_on:
#      - selenium-hub
#    extra_hosts:
#      - "localhost:host-gateway"   # ✅ to map host's localhost inside the container
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_SESSIONS=2
# 
#  edge:
#    image: selenium/node-edge:4.34.0
#    shm_size: 2gb
#    deploy:
#      replicas: 1
#    depends_on:
#      - selenium-hub
#    extra_hosts:
#      - "localhost:host-gateway"   # ✅ to map host's localhost inside the container
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_SESSIONS=2
 
  selenium-hub:
    image: selenium/hub:4.34.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
